### PR TITLE
Upgrade to react-native-firebase v5.0.0 and react-native 0.57.2

### PR DESCRIPTION
**Pull request by IjzerenHein**
This PR upgrades `react-native-firebase-starter` to use the latest 5.0.0 version of `react-native-firebase`. Additionally, the project was updated to the latest version or react-native, v0.57.1

### Upgrades:
- Upgraded `react-native-firebase` to 5.0.0
- Upgraded `react-native` to 0.57.1 (and `React` 16.5.0)
- Upgraded firebase pods to version 5.9.0 (and crashlytics/fabric to the latest version)
- Upgraded android firebase deps to their latest versions
- Added compatibility with XCode 10

### Other changes
- Removed `package-lock.json` which interferes with other packagers such as `yarn`
- Removed Firebase Crash reporting
- Added script `yarn apk` to test building Android APKs

### RN0.57.2 regression bug
Althrough RN 0.57.2 is the latest version, this version contains a regression issue with the bundler which makes that version not work out of the box (a workaround by starting a new bundler with cache-reset is required). I've therefore reverted back to 0.57.1 which runs just fine. More info here:
https://github.com/facebook/react-native/issues/21490

### XCode 10 compatibility note
One important thing to note is that there are issues with building react-native v0.57 on XCode 10. This is apparently due to the fact that XCode 10 introduces a new build system and React-native supports it in part but not fully yet.. I tried many solutions to ensure the build succeeds, but found only one solid solution at this stage. This involves turning off the `new XCode 10 build system`, as outlined here: https://github.com/facebook/react-native/issues/19573
This setting is stored in the `WorkspaceSettings.xcsettings` file, and in time, should be removed again.

### CODE REVIEW

**Comment by Salakar** [comment]
@IjzerenHein thanks so much for this, really appreciate the help 👍 

I'll review first thing in the morning and get back to you.

Thanks again!

---
Loving `react-native-firebase` and the support we provide? Please consider supporting us with any of the below:

  - 👉  Back financially via [Open Collective](https://opencollective.com/react-native-firebase/donate)  
  - 👉  Follow [`React Native Firebase`](https://twitter.com/rnfirebase) and [`Invertase`](https://twitter.com/invertaseio) on Twitter 
  - 👉  Star this repo on GitHub ⭐️

**Comment by modawoud** [comment]
Works perfectly,
Thank you <3

**Comment by Salakar** [comment]
@IjzerenHein have just ran this locally with no problems, I updated a couple things directly on your branch such as Android SDK versions and the Gradle version.

Just trying to reproduce @modawoud issue at the moment before I merge.

**Comment by IjzerenHein** [comment]
Sweet! Glad to help out @Salakar :)

**Pull request merged**
